#!/usr/bin/env python3
"""Restore all English PYQs from demo seed data (keeps any existing rows)."""
import sys
sys.path.insert(0, ".")

from app.db.database import SessionLocal
from app.db.models import PastYearProblem, PastYearExamType, User

db = SessionLocal()
try:
    admin = db.query(User).filter(User.role == 'admin').first()
    if not admin:
        print("ERROR: No admin user found.")
        sys.exit(1)

    before = db.query(PastYearProblem).count()
    print(f"PYQs before restore: {before}")

    rows = [
        # ── History ──────────────────────────────────────────────────────────
        dict(year=2024, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="History", topic="Modern India", question_number="Q.5",
             question_text="With reference to the Indian National Movement, consider the following statements:\n"
                           "1. The Lucknow Pact of 1916 was a milestone for Hindu-Muslim unity.\n"
                           "2. Annie Besant launched the Home Rule League in 1916.",
             option_a="1 only", option_b="2 only",
             option_c="Both 1 and 2", option_d="Neither 1 nor 2",
             correct_option="C",
             explanation="Both statements are correct. The Lucknow Pact (1916) brought Congress and Muslim League together. Besant launched the Home Rule League the same year.",
             language="en"),
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="History", topic="Ancient India", question_number="Q.9",
             question_text="The term 'Dharmashastra' in ancient India primarily referred to:",
             option_a="Texts on statecraft and diplomacy",
             option_b="Sacred texts dealing with religious and legal duties",
             option_c="Astronomical and mathematical treatises",
             option_d="Epic poetry glorifying kings",
             correct_option="B",
             explanation="Dharmashastra refers to a genre of Sanskrit texts dealing with dharma—religious law, ethics, and the duties of individuals in society (e.g., Manusmriti).",
             language="en"),
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="History", topic="Medieval India", question_number="Q.14",
             question_text="Which Mughal emperor introduced the Mansabdari system in a comprehensive form?",
             option_a="Babur", option_b="Humayun", option_c="Akbar", option_d="Aurangzeb",
             correct_option="C",
             explanation="Akbar systematised the Mansabdari system which assigned ranks (mansabs) to military and civil officials, standardising hierarchy in the Mughal administration.",
             language="en"),
        # ── Geography ────────────────────────────────────────────────────────
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Geography", topic="Climatology", question_number="Q.18",
             question_text="Which of the following correctly explains 'El Niño'?",
             option_a="Cooling of eastern Pacific Ocean surface waters",
             option_b="Anomalous warming of central and eastern equatorial Pacific surface waters",
             option_c="Monsoon surge confined to the Arabian Sea only",
             option_d="Splitting of the subtropical jet stream over India",
             correct_option="B",
             explanation="El Niño is associated with anomalous warming of the central/eastern equatorial Pacific. It typically weakens the Indian summer monsoon.",
             language="en"),
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Geography", topic="Indian Rivers", question_number="Q.22",
             question_text="Which of the following rivers does NOT originate in India?",
             option_a="Godavari", option_b="Beas",
             option_c="Indus", option_d="Kaveri",
             correct_option="C",
             explanation="The Indus originates in Tibet (China), near Lake Mansarovar, before entering India through Jammu & Kashmir.",
             language="en"),
        dict(year=2021, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Geography", topic="World Geography", question_number="Q.7",
             question_text="'Atacama Desert' is located in which continent?",
             option_a="Africa", option_b="Australia",
             option_c="South America", option_d="North America",
             correct_option="C",
             explanation="The Atacama Desert is in South America, along the Pacific coast of Chile and Peru. It is one of the driest places on Earth.",
             language="en"),
        # ── Polity ───────────────────────────────────────────────────────────
        dict(year=2021, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Polity", topic="DPSP", question_number="Q.11",
             question_text="Which of the following Directive Principles were added by the 42nd Constitutional Amendment (1976)?",
             option_a="Only Article 39",
             option_b="Articles 39A and 48A",
             option_c="Only Article 48A",
             option_d="Articles 39A, 43A and 48A",
             correct_option="D",
             explanation="The 42nd Amendment (1976) added Articles 39A (free legal aid), 43A (workers' participation in management), and 48A (protection of environment).",
             language="en"),
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Polity", topic="Parliament", question_number="Q.31",
             question_text="Which of the following statements about the 'Zero Hour' in the Indian Parliament is correct?",
             option_a="It is provided for in the Constitution",
             option_b="It takes place just before Question Hour",
             option_c="It is an informal device allowing members to raise urgent public matters",
             option_d="It lasts exactly one hour every day",
             correct_option="C",
             explanation="Zero Hour is not mentioned in the Constitution or Rules of Procedure. It is an informal convention starting at noon (after Question Hour) where members raise urgent matters without prior notice.",
             language="en"),
        dict(year=2024, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Polity", topic="Fundamental Rights", question_number="Q.3",
             question_text="Article 21A of the Constitution of India provides for:",
             option_a="Right to life and personal liberty",
             option_b="Right to free and compulsory education for children aged 6–14",
             option_c="Right against exploitation",
             option_d="Right to constitutional remedies",
             correct_option="B",
             explanation="Article 21A, inserted by the 86th Amendment Act 2002, provides for free and compulsory education for children between 6 and 14 years of age as a Fundamental Right.",
             language="en"),
        # ── Economy ──────────────────────────────────────────────────────────
        dict(year=2020, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Economy", topic="Banking", question_number="Q.33",
             question_text="Cash Reserve Ratio (CRR) refers to the fraction of NDTL that banks must maintain:",
             option_a="With themselves as cash in their vaults",
             option_b="As deposits with the Reserve Bank of India",
             option_c="Invested in government and approved securities",
             option_d="In the form of gold reserves with RBI",
             correct_option="B",
             explanation="CRR is the percentage of a bank's Net Demand and Time Liabilities (NDTL) that it must keep as cash deposits with the RBI. It is a monetary policy instrument.",
             language="en"),
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Economy", topic="Fiscal Policy", question_number="Q.44",
             question_text="Which of the following is NOT included in the 'Revenue Budget' of the Government of India?",
             option_a="Tax revenues",
             option_b="Interest payments on past debt",
             option_c="Loans given to state governments",
             option_d="Grants given to state governments",
             correct_option="C",
             explanation="Loans given to state governments are a capital expenditure and are part of the Capital Budget, not the Revenue Budget.",
             language="en"),
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Economy", topic="International Trade", question_number="Q.50",
             question_text="'Most Favoured Nation (MFN)' status in the context of the WTO means:",
             option_a="Giving preferential tariff to the most important trading partner only",
             option_b="Treating all WTO member nations equally in trade matters",
             option_c="Reducing tariffs to zero for the granting country",
             option_d="Allowing free movement of labour between member countries",
             correct_option="B",
             explanation="MFN (now called Permanent Normal Trade Relations) is a principle in WTO trade law that requires equal treatment of all member nations—any advantage given to one must be extended to all.",
             language="en"),
        dict(year=2024, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Economy", topic="Inflation", question_number="Q.27",
             question_text="Which index is primarily used by the RBI for its inflation targeting framework in India?",
             option_a="Wholesale Price Index (WPI)",
             option_b="Consumer Price Index – Industrial Workers (CPI-IW)",
             option_c="Consumer Price Index – Combined (CPI-C)",
             option_d="GDP Deflator",
             correct_option="C",
             explanation="Following the FRBM amendment and the Monetary Policy Framework Agreement (2015), RBI targets CPI-Combined (CPI-C) for inflation targeting, with a target of 4% ± 2%.",
             language="en"),
        # ── Environment ──────────────────────────────────────────────────────
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Environment", topic="Biodiversity", question_number="Q.42",
             question_text="Which one of the following is a primary consumer in a grassland ecosystem?",
             option_a="Grass", option_b="Grasshopper",
             option_c="Snake", option_d="Hawk",
             correct_option="B",
             explanation="Primary consumers are herbivores that directly feed on producers. In a grassland, grasshoppers eat grass and are therefore primary consumers.",
             language="en"),
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Environment", topic="Climate Change", question_number="Q.60",
             question_text="'Nationally Determined Contributions (NDCs)' are submitted by countries under which agreement?",
             option_a="Kyoto Protocol", option_b="Montreal Protocol",
             option_c="Paris Agreement", option_d="UNFCCC itself",
             correct_option="C",
             explanation="NDCs are pledges made by each country party to the Paris Agreement (2015), outlining their plans to reduce greenhouse gas emissions and adapt to climate change.",
             language="en"),
        dict(year=2024, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Environment", topic="Protected Areas", question_number="Q.38",
             question_text="A 'Biosphere Reserve' in India differs from a National Park primarily in that:",
             option_a="Biosphere Reserves allow no human activity at all",
             option_b="Biosphere Reserves have a buffer zone allowing sustainable human use",
             option_c="National Parks are managed by the central government only",
             option_d="National Parks include marine areas while Biosphere Reserves do not",
             correct_option="B",
             explanation="A Biosphere Reserve has three zones: core (strictly protected), buffer (limited research/tourism), and transition (human settlements and sustainable use). National Parks permit no human habitation at all.",
             language="en"),
        # ── Science & Technology ─────────────────────────────────────────────
        dict(year=2023, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Science & Technology", topic="Space", question_number="Q.71",
             question_text="India's 'Chandrayaan-3' mission successfully made a soft landing near the Moon's:",
             option_a="Equatorial region", option_b="North pole",
             option_c="South pole", option_d="Far side",
             correct_option="C",
             explanation="Chandrayaan-3 achieved a historic soft landing near the Moon's south pole on 23 August 2023, making India the first country to land a spacecraft in that region.",
             language="en"),
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Science & Technology", topic="Biotechnology", question_number="Q.65",
             question_text="CRISPR-Cas9 technology is primarily used for:",
             option_a="Protein synthesis in industrial scale",
             option_b="Precise editing of DNA sequences in living organisms",
             option_c="Producing vaccines through viral vectors only",
             option_d="Cloning of whole organisms from somatic cells",
             correct_option="B",
             explanation="CRISPR-Cas9 is a revolutionary gene-editing tool that allows scientists to precisely cut and modify DNA sequences in any organism, with wide applications in medicine and agriculture.",
             language="en"),
        dict(year=2024, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Science & Technology", topic="Defence", question_number="Q.80",
             question_text="'DRDO's Agni-V missile' is best described as a:",
             option_a="Short-range surface-to-air missile",
             option_b="Intercontinental ballistic missile (ICBM) with a range over 5,000 km",
             option_c="Supersonic cruise missile",
             option_d="Anti-tank guided missile",
             correct_option="B",
             explanation="Agni-V is an intercontinental ballistic missile developed by DRDO with a range of over 5,000 km (some estimates 7,000–8,000 km), capable of carrying nuclear warheads.",
             language="en"),
        # ── Art & Culture ─────────────────────────────────────────────────────
        dict(year=2022, exam_type=PastYearExamType.PRELIMS, paper="CSE Prelims",
             subject="Art & Culture", topic="Classical Dance", question_number="Q.16",
             question_text="'Manipuri' classical dance form originated in which state of India?",
             option_a="Assam", option_b="Odisha",
             option_c="Manipur", option_d="Meghalaya",
             correct_option="C",
             explanation="Manipuri is one of the eight classical dance forms of India, originating in Manipur. It is known for its graceful movements depicting Vaishnavite themes.",
             language="en"),
        # ── Mains subjective ─────────────────────────────────────────────────
        dict(year=2023, exam_type=PastYearExamType.MAINS, paper="GS Paper II",
             subject="Polity", topic="Federalism", question_number="Q.4",
             question_text="Cooperative federalism has been largely replaced by competitive federalism in recent years. Critically examine this statement in the context of centre-state relations in India.",
             option_a=None, option_b=None, option_c=None, option_d=None,
             correct_option=None,
             explanation="A well-structured answer should cover: NITI Aayog vs Planning Commission, Finance Commission recommendations, GST Council, state competition for investment, inter-state river disputes.",
             language="en"),
        dict(year=2022, exam_type=PastYearExamType.MAINS, paper="GS Paper III",
             subject="Economy", topic="Infrastructure", question_number="Q.7",
             question_text="What are the key challenges in infrastructure financing in India? Critically analyse the role of National Infrastructure Pipeline (NIP) in addressing these challenges.",
             option_a=None, option_b=None, option_c=None, option_d=None,
             correct_option=None,
             explanation="Cover: financing gap, PPP model issues, land acquisition bottlenecks, regulatory delays; NIP's contribution—project pipeline, hybrid annuity model, InvITs.",
             language="en"),
        dict(year=2024, exam_type=PastYearExamType.MAINS, paper="GS Paper I",
             subject="History", topic="Social Reform", question_number="Q.2",
             question_text="Critically examine the contribution of Raja Ram Mohan Roy to the social and religious reform movements in 19th century India.",
             option_a=None, option_b=None, option_c=None, option_d=None,
             correct_option=None,
             explanation="Key points: Brahmo Samaj (1828), campaign against Sati (Bengal Sati Regulation 1829), women's education, rationalist outlook, press freedom advocacy.",
             language="en"),
    ]

    items = [PastYearProblem(**{**r, 'created_by': admin.id}) for r in rows]
    db.add_all(items)
    db.commit()
    after = db.query(PastYearProblem).count()
    print(f"Restored {after - before} English PYQs. Total now: {after}")
finally:
    db.close()
